import React,{useEffect,useState} from 'react';
import {collection,getDocs,orderBy,query,updateDoc,doc} from 'firebase/firestore';
import {adminDb} from './firebase';
import {RotateCcw,RefreshCw,ChevronDown,MapPin,Phone,Mail,Package} from 'lucide-react';
import {toast} from 'react-hot-toast';
import './admin-dashboard.css';
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const requestStatuses=['requested','approved','processing','completed','rejected'];
export default function AdminReturns(){
 const [requests,setRequests]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(null),[busy,setBusy]=useState('');
 const load=async()=>{setLoading(true);try{const snap=await getDocs(query(collection(adminDb,'returns'),orderBy('createdAt','desc')));setRequests(snap.docs.map(d=>({id:d.id,...d.data()})))}catch(e){console.error(e);toast.error(e.code==='failed-precondition'?'Create the Firestore index for returns.createdAt first':'Could not load return requests')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const updateStatus=async(r,status)=>{setBusy(r.id);try{await updateDoc(doc(adminDb,'returns',r.id),{status,updatedAt:new Date()});setRequests(xs=>xs.map(x=>x.id===r.id?{...x,status}:x));toast.success('Request status updated')}catch(e){console.error(e);toast.error('Could not update request')}finally{setBusy('')}};
 return <section className="adminReturnSection"><div className="ordersHead"><div><p className="eyebrow">AFTER-SALES</p><h2>Return & <span>replacement requests.</span></h2><p>Review customer requests for damaged, defective, or mismatched items.</p></div><button className="adminsignout" onClick={load} disabled={loading}><RefreshCw size={16}/> {loading?'Loading...':'Refresh'}</button></div>{loading?<div className="empty">Loading requests...</div>:!requests.length?<div className="ordersEmpty"><RotateCcw size={40}/><h3>No return requests</h3><p>New customer return or replacement requests will appear here.</p></div>:<div className="ordersList">{requests.map(r=><div className={`orderCard adminReturnCard ${open===r.id?'expanded':''}`} key={r.id}><div className="orderTop"><div><b>{r.displayOrderId||r.orderId||r.id}</b><small>{r.customer?.name||'Customer'} · {r.customer?.phone||'No phone'}</small></div><strong>{money(r.total)}</strong><span className={`returnType ${r.type}`}>{r.type==='replacement'?<RefreshCw size={13}/>:<RotateCcw size={13}/>} {r.type==='replacement'?'Replacement':'Return'}</span><select value={r.status||'requested'} disabled={busy===r.id} onChange={e=>updateStatus(r,e.target.value)}>{requestStatuses.map(s=><option key={s}>{s}</option>)}</select><button className="orderToggle" onClick={()=>setOpen(open===r.id?null:r.id)}><ChevronDown size={18}/></button></div>{open===r.id&&<div className="orderDetails"><div className="detailGrid"><div><h4>Customer</h4><p><Mail size={14}/> {r.customer?.email||'—'}</p><p><Phone size={14}/> {r.customer?.phone||'—'}</p></div><div><h4>Delivery address</h4><p><MapPin size={14}/> {r.shipping?.address||'—'}, {r.shipping?.city||''}, {r.shipping?.state||''} - {r.shipping?.pincode||''}</p></div><div><h4>Request</h4><p><Package size={14}/> {r.reason||'Customer reported a mismatch or damage'}</p><p>Total: <b>{money(r.total)}</b></p></div></div><div className="orderedItems"><h4>Items</h4>{(r.items||[]).map((x,i)=><div key={i}><img src={x.image} alt=""/><span><b>{x.name}</b><small>Qty {x.qty} · {money(x.price)} each</small></span><strong>{money(x.price*x.qty)}</strong></div>)}</div></div>}</div>)}</div>}</section>;
}
