import React,{useEffect,useState} from 'react';
import {collection,deleteDoc,doc,getDocs,addDoc,updateDoc,getDoc} from 'firebase/firestore';
import {onAuthStateChanged,signInWithEmailAndPassword,signOut} from 'firebase/auth';
import {auth,db} from './firebase';
import {Plus,Trash2,LogOut,Edit3,X,Package} from 'lucide-react';
import {toast} from 'react-hot-toast';

const empty={name:'',category:'Automobile',price:'',rating:'5',stock:'0',image:'',description:''};
const num=v=>Number(v||0);

export default function Admin(){
  const [user,setUser]=useState(null),[checking,setChecking]=useState(true),[allowed,setAllowed]=useState(false);
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[loginBusy,setLoginBusy]=useState(false);
  const [products,setProducts]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false);
  useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);setAllowed(false);if(!u){setChecking(false);return}try{const snap=await getDoc(doc(db,'admins',u.uid));setAllowed(snap.exists())}catch(e){console.error(e);toast.error('Could not verify admin access')}finally{setChecking(false)}}),[]);
  useEffect(()=>{if(allowed)loadProducts()},[allowed]);
  async function loadProducts(){try{const snap=await getDocs(collection(db,'products'));setProducts(snap.docs.map(d=>({id:d.id,...d.data()})))}catch(e){console.error(e);toast.error(e.code==='permission-denied'?'Admin permissions are not enabled yet':'Could not load products')}}
  async function login(e){e.preventDefault();setLoginBusy(true);try{await signInWithEmailAndPassword(auth,email,password);toast.success('Signed in')}catch(e){toast.error(e.code==='auth/invalid-credential'?'Invalid email or password':e.message)}finally{setLoginBusy(false)}}
  function edit(p){setEditing(p.id);setForm({name:p.name||'',category:p.category||'Automobile',price:String(p.price??''),rating:String(p.rating??''),stock:String(p.stock??''),image:p.image||'',description:p.description||''});window.scrollTo({top:0,behavior:'smooth'})}
  function reset(){setEditing(null);setForm(empty)}
  async function save(e){e.preventDefault();if(!form.name.trim()||form.price===''||!form.image.trim()){toast.error('Name, price and image are required');return}setSaving(true);const payload={name:form.name.trim(),category:form.category,price:num(form.price),rating:num(form.rating),stock:num(form.stock),image:form.image.trim(),description:form.description.trim()};try{if(editing)await updateDoc(doc(db,'products',editing),payload);else await addDoc(collection(db,'products'),payload);toast.success(editing?'Product updated':'Product added');reset();await loadProducts()}catch(e){console.error(e);toast.error('Save failed. Check Firebase admin rules.')}finally{setSaving(false)}}
  async function remove(id){if(!confirm('Delete this product permanently?'))return;try{await deleteDoc(doc(db,'products',id));setProducts(p=>p.filter(x=>x.id!==id));toast.success('Product deleted')}catch(e){console.error(e);toast.error('Delete failed. Check Firebase admin rules.')}}
  if(checking)return <section className="admin page"><div className="empty">Checking admin access...</div></section>;
  if(!user)return <section className="admin page"><div className="adminlogin"><p className="eyebrow">MOTODC ADMIN</p><h1>Admin <span>login.</span></h1><p>Sign in with your Firebase Authentication account.</p><form onSubmit={login}><input type="email" placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="heroBtn" disabled={loginBusy}>{loginBusy?'Signing in...':'Sign in'}</button></form></div></section>;
  if(!allowed)return <section className="admin page"><div className="empty"><div><h2>Admin access not granted</h2><p>Your signed-in Firebase user does not have an <b>admins/{user.uid}</b> document.</p><button className="heroBtn" onClick={()=>signOut(auth)}>Sign out</button></div></div></section>;
  return <section className="admin page"><div className="adminhead"><div><p className="eyebrow">MOTODC ADMIN</p><h1>Product <span>manager.</span></h1><p>Manage the live Firestore catalog.</p></div><button className="adminsignout" onClick={()=>signOut(auth)}><LogOut size={16}/> Sign out</button></div><div className="adminlayout"><form className="adminform" onSubmit={save}><div className="formtitle"><h2>{editing?'Edit product':'Add product'}</h2>{editing&&<button type="button" onClick={reset}><X size={17}/></button>}</div><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Product name"/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Automobile</option><option>Motorcycle</option></select></label><div className="formrow"><label>Price (₹)<input type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Rating<input type="number" min="0" max="5" step="0.1" value={form.rating} onChange={e=>setForm({...form,rating:e.target.value})}/></label></div><label>Stock<input type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label>Image path<input value={form.image} onChange={e=>setForm({...form,image:e.target.value})} placeholder="/products/brake-disc.svg"/></label><label>Description<textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Product description"/></label><button className="heroBtn" disabled={saving}>{saving?'Saving...':editing?'Update product':<><Plus size={17}/> Add product</>}</button></form><div className="adminlist"><div className="listhead"><h2><Package size={20}/> Products</h2><b>{products.length}</b></div>{products.map(p=><div className="adminproduct" key={p.id}><img src={p.image} alt=""/><div><h3>{p.name}</h3><small>{p.category} · ₹{num(p.price).toLocaleString('en-IN')} · {p.stock} stock</small></div><button onClick={()=>edit(p)} title="Edit"><Edit3 size={16}/></button><button className="delete" onClick={()=>remove(p.id)} title="Delete"><Trash2 size={16}/></button></div>)}{!products.length&&<div className="empty">No products yet.</div>}</div></div></section>;
}
