import React,{useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {addDoc,collection,serverTimestamp} from 'firebase/firestore';
import {auth,db} from './firebase';
import {ArrowLeft,CheckCircle,MapPin,Phone,Mail,User,Wallet,Truck} from 'lucide-react';
import {toast} from 'react-hot-toast';

const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const getCart=()=>{try{return JSON.parse(localStorage.getItem('motodc-cart')||'[]')}catch{return[]}};
const clearCart=()=>{localStorage.removeItem('motodc-cart');window.dispatchEvent(new Event('cartchange'))};

export default function Checkout(){
 const nav=useNavigate();
 const [items]=useState(getCart());
 const [placed,setPlaced]=useState(null);
 const [loading,setLoading]=useState(false);
 const [form,setForm]=useState({name:auth.currentUser?.displayName||'',email:auth.currentUser?.email||'',phone:auth.currentUser?.phoneNumber||'',address:'',city:'',state:'',pincode:''});
 const [payment,setPayment]=useState('cod');
 const subtotal=items.reduce((a,x)=>a+Number(x.price||0)*Number(x.qty||1),0);
 const update=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async e=>{e.preventDefault();if(!items.length){toast.error('Your cart is empty');nav('/products');return}if(!/^[0-9]{10}$/.test(form.phone.replace(/\D/g,''))){toast.error('Enter a valid 10-digit phone number');return}if(!/^[0-9]{6}$/.test(form.pincode)){toast.error('Enter a valid 6-digit PIN code');return}setLoading(true);try{const orderId=`MDC-${Date.now().toString().slice(-8)}`;const ref=await addDoc(collection(db,'orders'),{orderId,userId:auth.currentUser?.uid||null,customer:{name:form.name,email:form.email,phone:form.phone},shipping:{address:form.address,city:form.city,state:form.state,pincode:form.pincode},items:items.map(x=>({id:x.id,name:x.name,category:x.category,price:Number(x.price||0),qty:Number(x.qty||1),image:x.image})),subtotal,total:subtotal,delivery:'FREE',paymentMethod:payment,paymentStatus:payment==='cod'?'pending':'pending',orderStatus:'placed',createdAt:serverTimestamp()});clearCart();setPlaced({orderId,docId:ref.id,total:subtotal});toast.success('Order placed successfully');}catch(err){console.error(err);toast.error('Could not place the order. Please try again.')}finally{setLoading(false)}};
 if(placed)return <section className="page checkoutPage"><div className="orderSuccess"><CheckCircle size={64}/><p className="eyebrow">ORDER CONFIRMED</p><h1>Thank you for your <span>order.</span></h1><p>Your order has been placed successfully.</p><div className="orderNumber">Order ID <strong>{placed.orderId}</strong></div><h2>{money(placed.total)}</h2><div className="successActions"><button className="heroBtn" onClick={()=>nav('/products')}>Continue Shopping</button><button className="secondaryBtn" onClick={()=>nav('/')}>Back Home</button></div></div></section>;
 if(!items.length)return <section className="page empty"><h2>Your cart is empty</h2><button className="heroBtn" onClick={()=>nav('/products')}>Browse Products</button></section>;
 return <section className="page checkoutPage"><button className="backBtn" onClick={()=>nav('/cart')}><ArrowLeft size={16}/> Back to Cart</button><div className="pagehead"><p className="eyebrow">SECURE CHECKOUT</p><h1>Complete your <span>order.</span></h1><p>Enter your delivery details and choose a payment method.</p></div><div className="checkoutLayout"><form className="checkoutForm" onSubmit={submit}><div className="checkoutBlock"><h2><User size={19}/> Contact details</h2><div className="formGrid"><label>Full name<input required name="name" value={form.name} onChange={update} placeholder="Your full name"/></label><label>Email<input required type="email" name="email" value={form.email} onChange={update} placeholder="you@example.com"/></label><label>Phone<input required name="phone" value={form.phone} onChange={update} placeholder="10-digit mobile number" maxLength={10}/></label></div></div><div className="checkoutBlock"><h2><MapPin size={19}/> Delivery address</h2><div className="formGrid"><label className="full">Address<input required name="address" value={form.address} onChange={update} placeholder="House / street / area"/></label><label>City<input required name="city" value={form.city} onChange={update} placeholder="City"/></label><label>State<input required name="state" value={form.state} onChange={update} placeholder="State"/></label><label>PIN code<input required name="pincode" value={form.pincode} onChange={update} placeholder="6-digit PIN" maxLength={6}/></label></div></div><div className="checkoutBlock"><h2><Wallet size={19}/> Payment method</h2><div className="paymentOptions"><label className={payment==='cod'?'selected':''}><input type="radio" name="payment" checked={payment==='cod'} onChange={()=>setPayment('cod')}/><span><b>Cash on Delivery</b><small>Pay when your order arrives</small></span></label><label className={payment==='online'?'selected':''}><input type="radio" name="payment" checked={payment==='online'} onChange={()=>setPayment('online')}/><span><b>Online Payment</b><small>Payment gateway can be connected next</small></span></label></div></div><button className="heroBtn placeOrder" disabled={loading}>{loading?'Placing Order...':<>Place Order · {money(subtotal)}</>}</button></form><aside className="checkoutSummary"><h2>Order Summary</h2>{items.map(x=><div className="summaryItem" key={x.id}><img src={x.image} alt=""/><div><b>{x.name}</b><small>Qty {x.qty}</small></div><strong>{money(x.price*x.qty)}</strong></div>)}<hr/><p>Subtotal <b>{money(subtotal)}</b></p><p>Delivery <b>FREE</b></p><h3>Total <span>{money(subtotal)}</span></h3><div className="trust"><Truck size={17}/> Free delivery on this order</div></aside></div></section>;
}
