import React,{useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {addDoc,collection,serverTimestamp} from 'firebase/firestore';
import {auth,db} from './firebase';
import {ArrowLeft,CheckCircle,MapPin,Wallet,Truck,LogIn,ShieldCheck} from 'lucide-react';
import {toast} from 'react-hot-toast';
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const getCart=()=>{try{return JSON.parse(localStorage.getItem('motodc-cart')||'[]')}catch{return[]}};
const clearCart=()=>{localStorage.removeItem('motodc-cart');window.dispatchEvent(new Event('cartchange'))};
const loadRazorpay=()=>new Promise((resolve,reject)=>{if(window.Razorpay)return resolve(true);const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>resolve(true);s.onerror=()=>reject(new Error('Payment gateway could not load'));document.body.appendChild(s)});
export default function Checkout(){
 const nav=useNavigate(),[items]=useState(getCart()),[placed,setPlaced]=useState(null),[loading,setLoading]=useState(false),user=auth.currentUser;
 const [form,setForm]=useState({name:user?.displayName||'',email:user?.email||'',phone:user?.phoneNumber?.replace(/^\+91/,'')||'',address:'',city:'',state:'',pincode:''});
 const [payment,setPayment]=useState('cod');
 const subtotal=items.reduce((a,x)=>a+Number(x.price||0)*Number(x.qty||1),0);const update=e=>setForm({...form,[e.target.name]:e.target.value});
 if(!user)return <section className="page empty checkoutLogin"><div><LogIn size={42}/><p className="eyebrow">ACCOUNT REQUIRED</p><h2>Sign in to complete your order</h2><p>Please sign in before placing an order so your order can be securely linked to your account.</p><button className="heroBtn" onClick={()=>nav('/account')}>Sign In</button></div></section>;
 const validate=()=>{if(!items.length){toast.error('Your cart is empty');nav('/products');return false}if(!/^[0-9]{10}$/.test(form.phone.replace(/\D/g,''))){toast.error('Enter a valid 10-digit phone number');return false}if(!/^[0-9]{6}$/.test(form.pincode)){toast.error('Enter a valid 6-digit PIN code');return false}return true};
 const placeCod=async()=>{const orderId=`MDC-${Date.now().toString().slice(-8)}`;await addDoc(collection(db,'orders'),{orderId,userId:user.uid,customer:{name:form.name,email:form.email,phone:form.phone},shipping:{address:form.address,city:form.city,state:form.state,pincode:form.pincode},items:items.map(x=>({id:x.id,name:x.name,category:x.category,price:Number(x.price||0),qty:Number(x.qty||1),image:x.image})),subtotal,total:subtotal,delivery:'FREE',paymentMethod:'cod',paymentStatus:'pending',orderStatus:'placed',createdAt:serverTimestamp()});clearCart();setPlaced({orderId,total:subtotal});toast.success('Order placed successfully')};
 const placeOnline=async()=>{await loadRazorpay();const token=await user.getIdToken();const create=await fetch('/api/create-payment',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({items:items.map(x=>({id:x.id,qty:x.qty})),amount:subtotal})});const created=await create.json();if(!create.ok)throw new Error(created.error||'Could not start payment');const options={key:created.keyId,amount:created.amount,currency:created.currency,name:'MotoDC',description:'Automotive parts order',order_id:created.orderId,prefill:{name:form.name,email:form.email,contact:form.phone},theme:{color:'#ff3157'},handler:async response=>{try{const verify=await fetch('/api/verify-payment',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({razorpay_order_id:response.razorpay_order_id,razorpay_payment_id:response.razorpay_payment_id,razorpay_signature:response.razorpay_signature,customer:{name:form.name,email:form.email,phone:form.phone},shipping:{address:form.address,city:form.city,state:form.state,pincode:form.pincode},items:created.items,total:subtotal,paymentMethod:'online'})});const result=await verify.json();if(!verify.ok)throw new Error(result.error||'Payment verification failed');clearCart();setPlaced({orderId:result.orderId,total:result.total});toast.success('Payment verified and order placed')}catch(e){toast.error(e.message||'Payment verification failed')}}};const rzp=new window.Razorpay(options);rzp.on('payment.failed',response=>toast.error(response.error?.description||'Payment failed'));rzp.open()};
 const submit=async e=>{e.preventDefault();if(!validate())return;setLoading(true);try{if(payment==='cod')await placeCod();else await placeOnline()}catch(err){console.error(err);toast.error(err.message||'Could not place the order')}finally{setLoading(false)}};
 if(placed)return <section className="page checkoutPage"><div className="orderSuccess"><CheckCircle size={64}/><p className="eyebrow">ORDER CONFIRMED</p><h1>Thank you for your <span>order.</span></h1><p>Your order has been placed successfully.</p><div className="orderNumber">Order ID <strong>{placed.orderId}</strong></div><h2>{money(placed.total)}</h2><div className="successActions"><button className="heroBtn" onClick={()=>nav('/products')}>Continue Shopping</button><button className="secondaryBtn" onClick={()=>nav('/')}>Back Home</button></div></div></section>;
 if(!items.length)return <section className="page empty"><h2>Your cart is empty</h2><button className="heroBtn" onClick={()=>nav('/products')}>Browse Products</button></section>;
 return <section className="page checkoutPage"><button className="backBtn" onClick={()=>nav('/cart')}><ArrowLeft size={16}/> Back to Cart</button><div className="pagehead"><p className="eyebrow">SECURE CHECKOUT</p><h1>Complete your <span>order.</span></h1><p>Enter your delivery details and choose a payment method.</p></div><div className="checkoutLayout"><form className="checkoutForm" onSubmit={submit}><div className="checkoutBlock"><h2>Contact details</h2><div className="formGrid"><label>Full name<input required name="name" value={form.name} onChange={update} placeholder="Your full name"/></label><label>Email<input required type="email" name="email" value={form.email} onChange={update} placeholder="you@example.com"/></label><label>Phone<input required name="phone" value={form.phone} onChange={update} placeholder="10-digit mobile number" maxLength={10}/></label></div></div><div className="checkoutBlock"><h2><MapPin size={19}/> Delivery address</h2><div className="formGrid"><label className="full">Address<input required name="address" value={form.address} onChange={update} placeholder="House / street / area"/></label><label>City<input required name="city" value={form.city} onChange={update} placeholder="City"/></label><label>State<input required name="state" value={form.state} onChange={update} placeholder="State"/></label><label>PIN code<input required name="pincode" value={form.pincode} onChange={update} placeholder="6-digit PIN" maxLength={6}/></label></div></div><div className="checkoutBlock"><h2><Wallet size={19}/> Payment method</h2><div className="paymentOptions"><label className={payment==='cod'?'selected':''}><input type="radio" name="payment" checked={payment==='cod'} onChange={()=>setPayment('cod')}/><span><b>Cash on Delivery</b><small>Pay when your order arrives</small></span></label><label className={payment==='online'?'selected':''}><input type="radio" name="payment" checked={payment==='online'} onChange={()=>setPayment('online')}/><span><b>Online Payment</b><small>Secure Razorpay checkout</small></span></label></div></div><button className="heroBtn placeOrder" disabled={loading}>{loading?'Processing...':payment==='online'?<>Pay Securely · {money(subtotal)} <ShieldCheck size={17}/></>:<>Place Order · {money(subtotal)}</>}</button></form><aside className="checkoutSummary"><h2>Order Summary</h2>{items.map(x=><div className="summaryItem" key={x.id}><img src={x.image} alt=""/><div><b>{x.name}</b><small>Qty {x.qty}</small></div><strong>{money(x.price*x.qty)}</strong></div>)}<hr/><p>Subtotal <b>{money(subtotal)}</b></p><p>Delivery <b>FREE</b></p><h3>Total <span>{money(subtotal)}</span></h3><div className="trust"><Truck size={17}/> Free delivery on this order</div></aside></div></section>;
}
