import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useLocation} from 'react-router-dom';
import {collection,getDocs} from 'firebase/firestore';
import {db,auth} from './firebase';
import {onAuthStateChanged,signOut} from 'firebase/auth';
import Admin from './Admin';
import Auth from './Auth';
import Wishlist from './Wishlist';
import Checkout from './Checkout';
import Orders from './Orders';
import Returns from './Returns';
import {ShoppingCart,Search,Heart,Star,ArrowRight,Menu,X,Plus,Minus,Trash2,User,LogOut,Package} from 'lucide-react';
import {Toaster,toast} from 'react-hot-toast';
import './index.css';
import './account-hover.css';
const fallbackProducts=[
{id:'p1',name:'Performance Brake Disc Set',category:'Automobile',price:4599,rating:4.8,stock:24,image:'/products/brake-disc.svg'},
{id:'p2',name:'Racing Exhaust Muffler',category:'Motorcycle',price:6299,rating:4.6,stock:12,image:'/products/exhaust.svg'},
{id:'p3',name:'LED Headlamp Assembly',category:'Automobile',price:3199,rating:4.7,stock:40,image:'/products/headlamp.svg'},
{id:'p4',name:'Alloy Wheel Rim 17"',category:'Automobile',price:8999,rating:4.9,stock:8,image:'/products/wheel.svg'},
{id:'p5',name:'Chain & Sprocket Kit',category:'Motorcycle',price:2799,rating:4.5,stock:33,image:'/products/chain.svg'},
{id:'p6',name:'Turbocharger Unit',category:'Automobile',price:24999,rating:4.9,stock:5,image:'/products/turbo.svg'},
{id:'p7',name:'Sports Bike Fairing Kit',category:'Motorcycle',price:15999,rating:4.4,stock:6,image:'/products/fairing.svg'},
{id:'p8',name:'High-Performance Air Filter',category:'Automobile',price:999,rating:4.3,stock:60,image:'/products/air-filter.svg'}];
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function getCart(){try{return JSON.parse(localStorage.getItem('motodc-cart')||'[]')}catch{return[]}}
function saveCart(c){localStorage.setItem('motodc-cart',JSON.stringify(c));window.dispatchEvent(new Event('cartchange'))}
function addToCart(p,qty=1){if(Number(p.stock)<=0){toast.error(`${p.name} is out of stock`);return}const c=getCart(),i=c.findIndex(x=>x.id===p.id);if(i>=0)c[i].qty=Math.min(c[i].qty+qty,p.stock);else c.push({...p,qty:Math.min(qty,p.stock)});saveCart(c);toast.success(`${p.name} added to cart`)}
function getWishlist(){try{return JSON.parse(localStorage.getItem('motodc-wishlist')||'[]')}catch{return[]}}
function saveWishlist(w){localStorage.setItem('motodc-wishlist',JSON.stringify(w));window.dispatchEvent(new Event('wishlistchange'))}
function toggleWishlist(p){const w=getWishlist(),exists=w.some(x=>x.id===p.id),next=exists?w.filter(x=>x.id!==p.id):[...w,{...p}];saveWishlist(next);toast.success(exists?'Removed from wishlist':`${p.name} added to wishlist`);return !exists}
function useProducts(){const [data,setData]=useState(fallbackProducts),[loading,setLoading]=useState(true);React.useEffect(()=>{let active=true;(async()=>{try{const snap=await getDocs(collection(db,'products'));if(active&&snap.size)setData(snap.docs.map(d=>({id:d.id,...d.data()})))}catch(e){console.error('Firestore products error:',e)}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);return {data,loading}}
function ThemeToggle(){const [theme,setTheme]=useState(()=>localStorage.getItem('motodc-theme')||'dark');React.useEffect(()=>{document.body.classList.toggle('light-theme',theme==='light');localStorage.setItem('motodc-theme',theme)},[theme]);const toggle=()=>{const next=theme==='dark'?'light':'dark';setTheme(next);toast.success(`${next==='light'?'Light':'Dark'} mode enabled`)};return <button className="themeToggle" onClick={toggle} aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`} title={`Switch to ${theme==='dark'?'light':'dark'} mode`}><span className="themeIcon" aria-hidden="true">{theme==='dark'?'🌞':'🌙'}</span></button>}
function Header(){const nav=useNavigate(),[open,setOpen]=useState(false),[q,setQ]=useState(''),[count,setCount]=useState(getCart().reduce((a,x)=>a+x.qty,0)),[wishCount,setWishCount]=useState(getWishlist().length),[user,setUser]=useState(auth.currentUser),location=useLocation();React.useEffect(()=>{const f=()=>setCount(getCart().reduce((a,x)=>a+x.qty,0));addEventListener('cartchange',f);return()=>removeEventListener('cartchange',f)},[]);React.useEffect(()=>{const f=()=>setWishCount(getWishlist().length);addEventListener('wishlistchange',f);return()=>removeEventListener('wishlistchange',f)},[]);React.useEffect(()=>onAuthStateChanged(auth,setUser),[]);const search=e=>{e.preventDefault();nav('/products'+(q?`?q=${encodeURIComponent(q)}`:''));setOpen(false)};const logout=async()=>{try{await signOut(auth);toast.success('Signed out successfully');nav('/account',{replace:true})}catch{toast.error('Could not sign out')}};const displayName=user?.displayName||user?.email?.split('@')[0]||'Account';const isAdmin=location.pathname==='/admin';return <header><div className="nav">{!isAdmin&&<button className="mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>}{isAdmin?<span className="logo" aria-label="MotoDC">Moto<span>DC</span></span>:<a className="logo" onClick={()=>nav('/')}>Moto<span>DC</span></a>}{!isAdmin&&<nav className={open?'open':''}><a onClick={()=>{nav('/');setOpen(false)}}>Home</a><a onClick={()=>{nav('/products');setOpen(false)}}>Products</a><a onClick={()=>{nav('/products/auto');setOpen(false)}}>Automobile</a><a onClick={()=>{nav('/products/bike');setOpen(false)}}>Motorcycle</a>{user&&<a onClick={()=>{nav('/orders');setOpen(false)}}>My Orders</a>}</nav>}{!isAdmin&&<form onSubmit={search} className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search parts..."/></form>}<ThemeToggle/>{!isAdmin&&<div className={`accountWrap${user?' signedIn':''}`}>{user?<><button className="account accountName" aria-label="Signed-in user">{displayName}</button><div className="accountMenu"><button onClick={()=>nav('/orders')}><Package size={15}/> My Orders</button><button onClick={logout}><LogOut size={15}/> Sign out</button></div></div>:<button className="account" aria-label="Account" onClick={()=>nav('/account')}><User size={20}/></button>}</div></div>{!isAdmin&&<><button className="wishlistNav" onClick={()=>nav('/wishlist')} aria-label="Wishlist" title="Wishlist"><Heart size={21} fill={location.pathname==='/wishlist'?'currentColor':'none'}/><b>{wishCount}</b></button><button className="cart" onClick={()=>nav('/cart')} aria-label="Shopping Cart" title="Shopping Cart"><ShoppingCart size={21}/><b>{count}</b></button></>}</header>}
function Card({p}){const nav=useNavigate();const [wish,setWish]=useState(()=>getWishlist().some(x=>x.id===p.id));React.useEffect(()=>{const sync=()=>setWish(getWishlist().some(x=>x.id===p.id));addEventListener('wishlistchange',sync);return()=>removeEventListener('wishlistchange',sync)},[p.id]);const handleWish=()=>setWish(toggleWishlist(p));const outOfStock=Number(p.stock)<=0;return <article className="card"><div className="pic"><img src={p.image} alt={p.name}/><span>{p.category}</span><button onClick={handleWish} className={`heart ${wish?'wishActive':''}`} aria-label={wish?'Remove from wishlist':'Add to wishlist'}><Heart size={17} fill={wish?'#ff3157':'none'} strokeWidth={wish?2.5:2}/></button></div><div className="cardbody"><div className="rating"><Star size={14} fill="currentColor"/> {p.rating} <em>{outOfStock?'Out of stock':`${p.stock} in stock`}</em></div><h3 onClick={()=>nav('/products/'+p.id)}>{p.name}</h3><strong>{money(p.price)}</strong><div className="actions"><button disabled={outOfStock} onClick={()=>addToCart(p)}>{outOfStock?'Out of Stock':'Add to Cart'}</button><button disabled={outOfStock} className="primary" onClick={()=>{addToCart(p);if(!outOfStock)nav('/cart')}}>{outOfStock?'Unavailable':'Buy Now'}</button></div></div></article>}
function Products({forced}){const {data:products,loading}=useProducts();const params=new URLSearchParams(location.search),[cat,setCat]=useState(forced||'All'),[sort,setSort]=useState('featured'),[q,setQ]=useState(params.get('q')||'');const list=useMemo(()=>products.filter(p=>(cat==='All'||p.category===cat)&&p.name.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:sort==='rating'?b.rating-a.rating:0),[products,cat,q,sort]);return <section className="page"><div className="pagehead"><p className="eyebrow">MOTODC CATALOG</p><h1>Find the right <span>part.</span></h1><p>Premium automobile and motorcycle spare parts.</p></div><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products..."/><div>{['All','Automobile','Motorcycle'].map(x=><button className={cat===x?'active':''} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="rating">Top rated</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div>{loading?<div className="empty">Loading products...</div>:<><div className="grid">{list.map(p=><Card key={p.id} p={p}/>)}</div>{!list.length&&<div className="empty">No products found.</div>}</>}</section>}
function Home(){const nav=useNavigate();const {data:products}=useProducts();return <><section className="hero"><div><p className="eyebrow">PREMIUM AUTOMOTIVE PARTS</p><h1>Built for the <span>road.</span><br/>Made for you.</h1><p>Genuine-quality parts for cars and motorcycles. Shop confidently with fast delivery and dependable support.</p><button className="heroBtn" onClick={()=>nav('/products')}>Shop Parts <ArrowRight size={18}/></button></div><div className="heroVisual"><div className="orb">MDC</div></div></section><section className="stats"><div><b>5,000+</b><span>Products</span></div><div><b>12,000+</b><span>Customers</span></div><div><b>150+</b><span>Brands</span></div><div><b>4.8/5</b><span>Average rating</span></div></section><section className="section"><div className="sectionhead"><div><p className="eyebrow">SHOP BY CATEGORY</p><h2>Choose your machine</h2></div><button onClick={()=>nav('/products')}>View all <ArrowRight size={16}/></button></div><div className="categories"><button onClick={()=>nav('/products/auto')}><span>🚗</span><b>Automobile</b><small>Brakes, engines, lighting & body parts</small></button><button onClick={()=>nav('/products/bike')}><span>🏍️</span><b>Motorcycle</b><small>Exhausts, chains, fairings & more</small></button></div></section><section className="section"><div className="sectionhead"><div><p className="eyebrow">FEATURED</p><h2>Popular parts</h2></div><button onClick={()=>nav('/products')}>Browse catalog <ArrowRight size={16}/></button></div><div className="grid">{products.slice(0,4).map(p=><Card key={p.id} p={p}/>)}</div></section></>}
function Detail(){const id=location.pathname.split('/').pop(),{data:products}=useProducts(),p=products.find(x=>x.id===id),[qty,setQty]=useState(1),nav=useNavigate();if(!p)return <div className="empty page"><h2>Product not found</h2></div>;const outOfStock=Number(p.stock)<=0;return <section className="detail page"><img src={p.image} alt={p.name}/><div><p className="eyebrow">{p.category}</p><h1>{p.name}</h1><div className="rating"><Star size={15} fill="currentColor"/> {p.rating} · {outOfStock?'Out of stock':`${p.stock} in stock`}</div><h2>{money(p.price)}</h2><p>{p.description||'Premium-quality replacement part designed for dependable performance. Check compatibility with your vehicle before ordering.'}</p><div className="qty"><button disabled={outOfStock} onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={16}/></button><b>{qty}</b><button disabled={outOfStock} onClick={()=>setQty(Math.min(p.stock,qty+1))}><Plus size={16}/></button></div><button className="heroBtn" disabled={outOfStock} onClick={()=>{addToCart(p,qty);nav('/cart')}}>{outOfStock?'Out of Stock':'Add to Cart'} <ShoppingCart size={18}/></button></div></section>}
function Cart(){const [items,setItems]=useState(getCart());const update=(c)=>{setItems(c);saveCart(c)};const subtotal=items.reduce((a,x)=>a+x.price*x.qty,0);const nav=useNavigate();return <section className="page cartpage"><p className="eyebrow">YOUR ORDER</p><h1>Shopping <span>Cart</span></h1>{!items.length?<div className="empty"><h2>Your cart is empty</h2><p>Add some parts to get started.</p></div>:<div className="cartlayout"><div>{items.map(x=><div className="cartitem" key={x.id}><img src={x.image} alt={x.name}/><div><h3>{x.name}</h3><small>{x.category}</small><strong>{money(x.price)}</strong></div><div className="qty"><button onClick={()=>update(items.map(i=>i.id===x.id?{...i,qty:Math.max(1,i.qty-1)}:i))}><Minus size={14}/></button><b>{x.qty}</b><button onClick={()=>update(items.map(i=>i.id===x.id?{...i,qty:Math.min(i.stock,i.qty+1)}:i))}><Plus size={14}/></button></div><button className="delete" onClick={()=>update(items.filter(i=>i.id!==x.id))}><Trash2 size={17}/></button></div>)}</div><aside><h3>Order Summary</h3><p>Subtotal <b>{money(subtotal)}</b></p><p>Delivery <b>FREE</b></p><hr/><h2>Total <span>{money(subtotal)}</span></h2><button type="button" className="heroBtn" onClick={()=>nav('/checkout')}>Proceed to Checkout</button></aside></div>}</section>}
function App(){return <><Header/><main><RoutesFallback/></main><footer><b>Moto<span>DC</span></b><p>Premium parts. Better performance.</p><small>© 2026 MotoDC. All rights reserved.</small></footer></>}
function RoutesFallback(){const path=useLocation().pathname;if(path==='/admin')return <Admin/>;if(path==='/account')return auth.currentUser?<Home/>:<Auth/>;if(path==='/')return <Home/>;if(path==='/products')return <Products/>;if(path==='/products/auto')return <Products forced="Automobile"/>;if(path==='/products/bike')return <Products forced="Motorcycle"/>;if(path==='/wishlist')return <Wishlist/>;if(path==='/orders')return auth.currentUser?<Orders/>:<Auth/>;if(path==='/returns')return auth.currentUser?<Returns/>:<Auth/>;if(path==='/checkout')return <Checkout/>;if(path==='/cart')return <Cart/>;if(path.startsWith('/products/'))return <Detail/>;return <div className="empty page"><h1>Coming soon</h1><p>This section is being prepared for the next MotoDC build.</p></div>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/><Toaster position="top-right"/></BrowserRouter>);