export const majorSpareProducts = [
  {
    "name": "Honda Activa 6G Air Filter",
    "category": "Motorcycle",
    "brand": "Honda",
    "fitment": "Honda Activa 6G",
    "price": 499,
    "rating": 4.6,
    "stock": 48,
    "image": "/images/products/Honda_Activa_6G_Air_Filter.jpg",
    "description": "Honda Activa 6G air filter for Honda Activa 6G. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Honda Activa Front Brake Shoe Set",
    "category": "Motorcycle",
    "brand": "Honda",
    "fitment": "Honda Activa 5G/6G",
    "price": 699,
    "rating": 4.5,
    "stock": 32,
    "image": "/images/products/Honda_Activa_Front_Brake_Shoe_Set.jpg",
    "description": "Honda Activa front brake shoe set for Honda Activa 5G/6G. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Honda Shine Clutch Plate Set",
    "category": "Motorcycle",
    "brand": "Honda",
    "fitment": "Honda Shine 125",
    "price": 1199,
    "rating": 4.7,
    "stock": 24,
    "image": "/images/products/Honda_Shine_Clutch_Plate_Set.jpg",
    "description": "Honda Shine clutch plate set for Honda Shine 125. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Honda CB Shine Front Disc Pad",
    "category": "Motorcycle",
    "brand": "Honda",
    "fitment": "Honda Shine 125",
    "price": 749,
    "rating": 4.6,
    "stock": 38,
    "image": "/images/products/Honda_CB_Shine_Front_Disc_Pad.jpg",
    "description": "Honda CB Shine front disc pad for Honda Shine 125. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Honda Unicorn Chain Sprocket Kit",
    "category": "Motorcycle",
    "brand": "Honda",
    "fitment": "Honda Unicorn 150",
    "price": 1899,
    "rating": 4.7,
    "stock": 21,
    "image": "/images/products/Honda_Unicorn_Chain_Sprocket_Kit.jpg",
    "description": "Honda Unicorn chain sprocket kit for Honda Unicorn 150. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Hero Splendor Plus Air Filter",
    "category": "Motorcycle",
    "brand": "Hero",
    "fitment": "Hero Splendor Plus",
    "price": 399,
    "rating": 4.5,
    "stock": 65,
    "image": "/images/products/Hero_Splendor_Plus_Air_Filter.jpg",
    "description": "Hero Splendor Plus air filter for Hero Splendor Plus. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Hero Splendor Clutch Plate Set",
    "category": "Motorcycle",
    "brand": "Hero",
    "fitment": "Hero Splendor/Passion",
    "price": 999,
    "rating": 4.6,
    "stock": 29,
    "image": "/images/products/Hero_Splendor_Clutch_Plate_Set.jpg",
    "description": "Hero Splendor clutch plate set for Hero Splendor/Passion. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Hero Passion Pro Front Brake Shoe",
    "category": "Motorcycle",
    "brand": "Hero",
    "fitment": "Hero Passion Pro",
    "price": 649,
    "rating": 4.4,
    "stock": 42,
    "image": "/images/products/Hero_Passion_Pro_Front_Brake_Shoe.jpg",
    "description": "Hero Passion Pro front brake shoe for Hero Passion Pro. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Hero Glamour Chain Sprocket Kit",
    "category": "Motorcycle",
    "brand": "Hero",
    "fitment": "Hero Glamour 125",
    "price": 1699,
    "rating": 4.6,
    "stock": 18,
    "image": "/images/products/Hero_Glamour_Chain_Sprocket_Kit.jpg",
    "description": "Hero Glamour chain sprocket kit for Hero Glamour 125. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Hero Xtreme 160R Front Brake Pads",
    "category": "Motorcycle",
    "brand": "Hero",
    "fitment": "Hero Xtreme 160R",
    "price": 899,
    "rating": 4.7,
    "stock": 26,
    "image": "/images/products/Hero_Xtreme_160R_Front_Brake_Pads.jpg",
    "description": "Hero Xtreme 160R front brake pads for Hero Xtreme 160R. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Bajaj Pulsar 150 Air Filter",
    "category": "Motorcycle",
    "brand": "Bajaj",
    "fitment": "Bajaj Pulsar 150",
    "price": 449,
    "rating": 4.6,
    "stock": 54,
    "image": "/images/products/Bajaj_Pulsar_150_Air_Filter.jpg",
    "description": "Bajaj Pulsar 150 air filter for Bajaj Pulsar 150. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Bajaj Pulsar 150 Chain Sprocket Kit",
    "category": "Motorcycle",
    "brand": "Bajaj",
    "fitment": "Bajaj Pulsar 150",
    "price": 1799,
    "rating": 4.7,
    "stock": 20,
    "image": "/images/products/Bajaj_Pulsar_150_Chain_Sprocket_Kit.jpg",
    "description": "Bajaj Pulsar 150 chain sprocket kit for Bajaj Pulsar 150. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Bajaj Pulsar Front Disc Brake Pads",
    "category": "Motorcycle",
    "brand": "Bajaj",
    "fitment": "Bajaj Pulsar 150/180",
    "price": 799,
    "rating": 4.5,
    "stock": 34,
    "image": "/images/products/Bajaj_Pulsar_Front_Disc_Brake_Pads.jpg",
    "description": "Bajaj Pulsar front disc brake pads for Bajaj Pulsar 150/180. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Bajaj Platina Rear Brake Shoe",
    "category": "Motorcycle",
    "brand": "Bajaj",
    "fitment": "Bajaj Platina 100/110",
    "price": 599,
    "rating": 4.4,
    "stock": 46,
    "image": "/images/products/Bajaj_Platina_Rear_Brake_Shoe.jpg",
    "description": "Bajaj Platina rear brake shoe for Bajaj Platina 100/110. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Bajaj Dominar 400 Oil Filter",
    "category": "Motorcycle",
    "brand": "Bajaj",
    "fitment": "Bajaj Dominar 400",
    "price": 399,
    "rating": 4.8,
    "stock": 37,
    "image": "/images/products/Bajaj_Dominar_400_Oil_Filter.jpg",
    "description": "Bajaj Dominar 400 oil filter for Bajaj Dominar 400. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "TVS Apache RTR 160 Air Filter",
    "category": "Motorcycle",
    "brand": "TVS",
    "fitment": "TVS Apache RTR 160",
    "price": 549,
    "rating": 4.7,
    "stock": 41,
    "image": "/images/products/TVS_Apache_RTR_160_Air_Filter.jpg",
    "description": "TVS Apache RTR 160 air filter for TVS Apache RTR 160. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "TVS Apache RTR 160 Front Brake Pads",
    "category": "Motorcycle",
    "brand": "TVS",
    "fitment": "TVS Apache RTR 160",
    "price": 899,
    "rating": 4.6,
    "stock": 27,
    "image": "https://images.unsplash.com/photo-1558980664-10ea4b0e4d7d?auto=format&fit=crop&w=900&q=85",
    "description": "TVS Apache RTR 160 front brake pads for TVS Apache RTR 160. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "TVS Jupiter Drive Belt",
    "category": "Motorcycle",
    "brand": "TVS",
    "fitment": "TVS Jupiter 110",
    "price": 1299,
    "rating": 4.5,
    "stock": 23,
    "image": "/images/products/TVS_Jupiter_Drive_Belt.jpg",
    "description": "TVS Jupiter drive belt for TVS Jupiter 110. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "TVS Ntorq Clutch Shoe Set",
    "category": "Motorcycle",
    "brand": "TVS",
    "fitment": "TVS Ntorq 125",
    "price": 1199,
    "rating": 4.6,
    "stock": 31,
    "image": "/images/products/TVS_Ntorq_Clutch_Shoe_Set.jpg",
    "description": "TVS Ntorq clutch shoe set for TVS Ntorq 125. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "TVS Raider Chain Sprocket Kit",
    "category": "Motorcycle",
    "brand": "TVS",
    "fitment": "TVS Raider 125",
    "price": 1599,
    "rating": 4.7,
    "stock": 19,
    "image": "/images/products/TVS_Raider_Chain_Sprocket_Kit.jpg",
    "description": "TVS Raider chain sprocket kit for TVS Raider 125. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Yamaha FZ-FI Air Filter",
    "category": "Motorcycle",
    "brand": "Yamaha",
    "fitment": "Yamaha FZ/FZS FI",
    "price": 599,
    "rating": 4.7,
    "stock": 36,
    "image": "/images/products/Yamaha_FZ_FI_Air_Filter.jpg",
    "description": "Yamaha FZ-FI air filter for Yamaha FZ/FZS FI. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Yamaha R15 V3 Front Brake Pads",
    "category": "Motorcycle",
    "brand": "Yamaha",
    "fitment": "Yamaha R15 V3",
    "price": 999,
    "rating": 4.8,
    "stock": 22,
    "image": "/images/products/Yamaha_R15_V3_Front_Brake_Pads.jpg",
    "description": "Yamaha R15 V3 front brake pads for Yamaha R15 V3. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Yamaha R15 Chain Sprocket Kit",
    "category": "Motorcycle",
    "brand": "Yamaha",
    "fitment": "Yamaha R15 V3/V4",
    "price": 2299,
    "rating": 4.8,
    "stock": 15,
    "image": "https://images.unsplash.com/photo-1558980664-10ea4b0e4d7d?auto=format&fit=crop&w=900&q=85",
    "description": "Yamaha R15 chain sprocket kit for Yamaha R15 V3/V4. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Yamaha MT-15 Oil Filter",
    "category": "Motorcycle",
    "brand": "Yamaha",
    "fitment": "Yamaha MT-15",
    "price": 449,
    "rating": 4.7,
    "stock": 29,
    "image": "/images/products/Yamaha_MT_15_Oil_Filter.jpg",
    "description": "Yamaha MT-15 oil filter for Yamaha MT-15. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Yamaha FZ Rear Brake Shoe",
    "category": "Motorcycle",
    "brand": "Yamaha",
    "fitment": "Yamaha FZ V2",
    "price": 649,
    "rating": 4.5,
    "stock": 33,
    "image": "/images/products/Yamaha_FZ_Rear_Brake_Shoe.jpg",
    "description": "Yamaha FZ rear brake shoe for Yamaha FZ V2. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Suzuki Access 125 Air Filter",
    "category": "Motorcycle",
    "brand": "Suzuki",
    "fitment": "Suzuki Access 125",
    "price": 449,
    "rating": 4.6,
    "stock": 51,
    "image": "/images/products/Suzuki_Access_125_Air_Filter.jpg",
    "description": "Suzuki Access 125 air filter for Suzuki Access 125. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Suzuki Access 125 Drive Belt",
    "category": "Motorcycle",
    "brand": "Suzuki",
    "fitment": "Suzuki Access 125",
    "price": 1399,
    "rating": 4.5,
    "stock": 25,
    "image": "/images/products/Suzuki_Access_125_Drive_Belt.jpg",
    "description": "Suzuki Access 125 drive belt for Suzuki Access 125. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Suzuki Gixxer Front Disc Pads",
    "category": "Motorcycle",
    "brand": "Suzuki",
    "fitment": "Suzuki Gixxer 150",
    "price": 849,
    "rating": 4.6,
    "stock": 28,
    "image": "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=85",
    "description": "Suzuki Gixxer front disc pads for Suzuki Gixxer 150. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Suzuki Gixxer Chain Sprocket Kit",
    "category": "Motorcycle",
    "brand": "Suzuki",
    "fitment": "Suzuki Gixxer 150",
    "price": 1799,
    "rating": 4.7,
    "stock": 17,
    "image": "/images/products/Suzuki_Gixxer_Chain_Sprocket_Kit.jpg",
    "description": "Suzuki Gixxer chain sprocket kit for Suzuki Gixxer 150. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Suzuki Burgman Street Brake Shoe",
    "category": "Motorcycle",
    "brand": "Suzuki",
    "fitment": "Suzuki Burgman Street",
    "price": 699,
    "rating": 4.5,
    "stock": 30,
    "image": "/images/products/Suzuki_Burgman_Street_Brake_Shoe.jpg",
    "description": "Suzuki Burgman Street brake shoe for Suzuki Burgman Street. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Royal Enfield Classic 350 Air Filter",
    "category": "Motorcycle",
    "brand": "Royal Enfield",
    "fitment": "Royal Enfield Classic 350",
    "price": 649,
    "rating": 4.7,
    "stock": 44,
    "image": "/images/products/Royal_Enfield_Classic_350_Air_Filter.jpg",
    "description": "Royal Enfield Classic 350 air filter for Royal Enfield Classic 350. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Royal Enfield Classic 350 Front Brake Pads",
    "category": "Motorcycle",
    "brand": "Royal Enfield",
    "fitment": "Royal Enfield Classic 350",
    "price": 1099,
    "rating": 4.7,
    "stock": 24,
    "image": "/images/products/Royal_Enfield_Classic_350_Front_Brake_Pads.jpg",
    "description": "Royal Enfield Classic 350 front brake pads for Royal Enfield Classic 350. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Royal Enfield Classic 350 Chain Sprocket Kit",
    "category": "Motorcycle",
    "brand": "Royal Enfield",
    "fitment": "Royal Enfield Classic 350",
    "price": 2499,
    "rating": 4.8,
    "stock": 13,
    "image": "https://images.unsplash.com/photo-1558980394-0c6e2e4f1d7c?auto=format&fit=crop&w=900&q=85",
    "description": "Royal Enfield Classic 350 chain sprocket kit for Royal Enfield Classic 350. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Royal Enfield Hunter 350 Oil Filter",
    "category": "Motorcycle",
    "brand": "Royal Enfield",
    "fitment": "Royal Enfield Hunter 350",
    "price": 449,
    "rating": 4.8,
    "stock": 35,
    "image": "/images/products/Royal_Enfield_Hunter_350_Oil_Filter.jpg",
    "description": "Royal Enfield Hunter 350 oil filter for Royal Enfield Hunter 350. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Royal Enfield Meteor 350 Clutch Plate Set",
    "category": "Motorcycle",
    "brand": "Royal Enfield",
    "fitment": "Royal Enfield Meteor 350",
    "price": 1799,
    "rating": 4.6,
    "stock": 16,
    "image": "/images/products/Royal_Enfield_Meteor_350_Clutch_Plate_Set.jpg",
    "description": "Royal Enfield Meteor 350 clutch plate set for Royal Enfield Meteor 350. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "KTM Duke 200 Air Filter",
    "category": "Motorcycle",
    "brand": "KTM",
    "fitment": "KTM Duke 200",
    "price": 799,
    "rating": 4.7,
    "stock": 21,
    "image": "/images/products/KTM_Duke_200_Air_Filter.jpg",
    "description": "KTM Duke 200 air filter for KTM Duke 200. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "KTM Duke 200 Front Brake Pads",
    "category": "Motorcycle",
    "brand": "KTM",
    "fitment": "KTM Duke 200",
    "price": 1299,
    "rating": 4.8,
    "stock": 18,
    "image": "/images/products/KTM_Duke_200_Front_Brake_Pads.jpg",
    "description": "KTM Duke 200 front brake pads for KTM Duke 200. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "KTM Duke 250 Chain Sprocket Kit",
    "category": "Motorcycle",
    "brand": "KTM",
    "fitment": "KTM Duke 250",
    "price": 2999,
    "rating": 4.8,
    "stock": 11,
    "image": "/images/products/KTM_Duke_250_Chain_Sprocket_Kit.jpg",
    "description": "KTM Duke 250 chain sprocket kit for KTM Duke 250. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "KTM RC 200 Oil Filter",
    "category": "Motorcycle",
    "brand": "KTM",
    "fitment": "KTM RC 200",
    "price": 499,
    "rating": 4.7,
    "stock": 26,
    "image": "/images/products/KTM_RC_200_Oil_Filter.jpg",
    "description": "KTM RC 200 oil filter for KTM RC 200. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "KTM Adventure 390 Brake Pad Set",
    "category": "Motorcycle",
    "brand": "KTM",
    "fitment": "KTM Adventure 390",
    "price": 1499,
    "rating": 4.8,
    "stock": 12,
    "image": "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=85",
    "description": "KTM Adventure 390 brake pad set for KTM Adventure 390. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Bosch Motorcycle Iridium Spark Plug",
    "category": "Motorcycle",
    "brand": "Bosch",
    "fitment": "Multi-brand 4-stroke bikes",
    "price": 699,
    "rating": 4.8,
    "stock": 43,
    "image": "/images/products/Bosch_Motorcycle_Iridium_Spark_Plug.jpg",
    "description": "Bosch motorcycle iridium spark plug for Multi-brand 4-stroke bikes. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "NGK Iridium IX Spark Plug",
    "category": "Motorcycle",
    "brand": "NGK",
    "fitment": "Honda/Yamaha/Suzuki 125-250cc",
    "price": 749,
    "rating": 4.9,
    "stock": 52,
    "image": "/images/products/NGK_Iridium_IX_Spark_Plug.jpg",
    "description": "NGK iridium IX spark plug for Honda/Yamaha/Suzuki 125-250cc. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Endurance Universal Rear Shock Absorber",
    "category": "Motorcycle",
    "brand": "Endurance",
    "fitment": "Popular commuter motorcycles",
    "price": 1899,
    "rating": 4.5,
    "stock": 17,
    "image": "/images/products/Endurance_Universal_Rear_Shock_Absorber.jpg",
    "description": "Endurance universal rear shock absorber for Popular commuter motorcycles. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "SKF Steering Cone Bearing Kit",
    "category": "Motorcycle",
    "brand": "SKF",
    "fitment": "Bajaj/Hero/Honda/TVS",
    "price": 649,
    "rating": 4.7,
    "stock": 39,
    "image": "https://images.unsplash.com/photo-1558980664-10ea4b0e4d7d?auto=format&fit=crop&w=900&q=85",
    "description": "SKF steering cone bearing kit for Bajaj/Hero/Honda/TVS. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Uno Minda LED Motorcycle Headlamp",
    "category": "Motorcycle",
    "brand": "Uno Minda",
    "fitment": "12V motorcycles",
    "price": 1599,
    "rating": 4.6,
    "stock": 28,
    "image": "https://images.unsplash.com/photo-1558980394-0c6e2e4f1d7c?auto=format&fit=crop&w=900&q=85",
    "description": "Uno Minda LED motorcycle headlamp for 12V motorcycles. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Exide Two-Wheeler Battery 4Ah",
    "category": "Motorcycle",
    "brand": "Exide",
    "fitment": "12V motorcycles/scooters",
    "price": 1699,
    "rating": 4.7,
    "stock": 22,
    "image": "/images/products/Exide_Two_Wheeler_Battery_4Ah.jpg",
    "description": "Exide two-wheeler battery 4Ah for 12V motorcycles/scooters. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Amaron Two-Wheeler Battery 5Ah",
    "category": "Motorcycle",
    "brand": "Amaron",
    "fitment": "12V motorcycles/scooters",
    "price": 1899,
    "rating": 4.7,
    "stock": 20,
    "image": "/images/products/Amaron_Two_Wheeler_Battery_5Ah.jpg",
    "description": "Amaron two-wheeler battery 5Ah for 12V motorcycles/scooters. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Minda Universal Indicator Set",
    "category": "Motorcycle",
    "brand": "Minda",
    "fitment": "12V motorcycles",
    "price": 599,
    "rating": 4.4,
    "stock": 47,
    "image": "/images/products/Minda_Universal_Indicator_Set.jpg",
    "description": "Minda universal indicator set for 12V motorcycles. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Pricol Digital Motorcycle Speedometer",
    "category": "Motorcycle",
    "brand": "Pricol",
    "fitment": "Universal 12V bikes",
    "price": 2299,
    "rating": 4.5,
    "stock": 14,
    "image": "/images/products/Pricol_Digital_Motorcycle_Speedometer.jpg",
    "description": "Pricol digital motorcycle speedometer for Universal 12V bikes. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Maruti Suzuki Alto K10 Air Filter",
    "category": "Automobile",
    "brand": "Maruti Suzuki",
    "fitment": "Maruti Suzuki Alto K10",
    "price": 599,
    "rating": 4.6,
    "stock": 52,
    "image": "/images/products/Maruti_Suzuki_Alto_K10_Air_Filter.jpg",
    "description": "Maruti Suzuki Alto K10 air filter for Maruti Suzuki Alto K10. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Maruti Suzuki Swift Front Brake Pad Set",
    "category": "Automobile",
    "brand": "Maruti Suzuki",
    "fitment": "Maruti Suzuki Swift",
    "price": 1899,
    "rating": 4.7,
    "stock": 34,
    "image": "/images/products/Maruti_Suzuki_Swift_Front_Brake_Pad_Set.jpg",
    "description": "Maruti Suzuki Swift front brake pad set for Maruti Suzuki Swift. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Maruti Suzuki Swift Clutch Plate Kit",
    "category": "Automobile",
    "brand": "Maruti Suzuki",
    "fitment": "Maruti Suzuki Swift",
    "price": 4499,
    "rating": 4.7,
    "stock": 16,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=85",
    "description": "Maruti Suzuki Swift clutch plate kit for Maruti Suzuki Swift. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Maruti Suzuki Baleno Cabin Air Filter",
    "category": "Automobile",
    "brand": "Maruti Suzuki",
    "fitment": "Maruti Suzuki Baleno",
    "price": 699,
    "rating": 4.6,
    "stock": 43,
    "image": "/images/products/Maruti_Suzuki_Baleno_Cabin_Air_Filter.jpg",
    "description": "Maruti Suzuki Baleno cabin air filter for Maruti Suzuki Baleno. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Maruti Suzuki WagonR Oil Filter",
    "category": "Automobile",
    "brand": "Maruti Suzuki",
    "fitment": "Maruti Suzuki WagonR",
    "price": 349,
    "rating": 4.5,
    "stock": 61,
    "image": "/images/products/Maruti_Suzuki_WagonR_Oil_Filter.jpg",
    "description": "Maruti Suzuki WagonR oil filter for Maruti Suzuki WagonR. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Maruti Suzuki Brezza Front Brake Disc",
    "category": "Automobile",
    "brand": "Maruti Suzuki",
    "fitment": "Maruti Suzuki Brezza",
    "price": 3299,
    "rating": 4.7,
    "stock": 12,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=85",
    "description": "Maruti Suzuki Brezza front brake disc for Maruti Suzuki Brezza. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Hyundai i10 Air Filter",
    "category": "Automobile",
    "brand": "Hyundai",
    "fitment": "Hyundai Grand i10",
    "price": 649,
    "rating": 4.6,
    "stock": 47,
    "image": "/images/products/Hyundai_i10_Air_Filter.jpg",
    "description": "Hyundai i10 air filter for Hyundai Grand i10. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Hyundai i20 Front Brake Pad Set",
    "category": "Automobile",
    "brand": "Hyundai",
    "fitment": "Hyundai i20",
    "price": 2199,
    "rating": 4.7,
    "stock": 28,
    "image": "/images/products/Hyundai_i20_Front_Brake_Pad_Set.jpg",
    "description": "Hyundai i20 front brake pad set for Hyundai i20. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Hyundai Creta Cabin Filter",
    "category": "Automobile",
    "brand": "Hyundai",
    "fitment": "Hyundai Creta",
    "price": 799,
    "rating": 4.6,
    "stock": 39,
    "image": "/images/products/Hyundai_Creta_Cabin_Filter.jpg",
    "description": "Hyundai Creta cabin filter for Hyundai Creta. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Hyundai Venue Oil Filter",
    "category": "Automobile",
    "brand": "Hyundai",
    "fitment": "Hyundai Venue",
    "price": 399,
    "rating": 4.5,
    "stock": 55,
    "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85",
    "description": "Hyundai Venue oil filter for Hyundai Venue. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Hyundai Verna Clutch Kit",
    "category": "Automobile",
    "brand": "Hyundai",
    "fitment": "Hyundai Verna",
    "price": 6999,
    "rating": 4.8,
    "stock": 9,
    "image": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85",
    "description": "Hyundai Verna clutch kit for Hyundai Verna. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Tata Nexon Air Filter",
    "category": "Automobile",
    "brand": "Tata",
    "fitment": "Tata Nexon",
    "price": 699,
    "rating": 4.6,
    "stock": 42,
    "image": "/images/products/Tata_Nexon_Air_Filter.jpg",
    "description": "Tata Nexon air filter for Tata Nexon. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Tata Nexon Front Brake Pads",
    "category": "Automobile",
    "brand": "Tata",
    "fitment": "Tata Nexon",
    "price": 1999,
    "rating": 4.7,
    "stock": 24,
    "image": "/images/products/Tata_Nexon_Front_Brake_Pads.jpg",
    "description": "Tata Nexon front brake pads for Tata Nexon. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Tata Punch Cabin Filter",
    "category": "Automobile",
    "brand": "Tata",
    "fitment": "Tata Punch",
    "price": 749,
    "rating": 4.6,
    "stock": 31,
    "image": "/images/products/Tata_Punch_Cabin_Filter.jpg",
    "description": "Tata Punch cabin filter for Tata Punch. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Tata Altroz Oil Filter",
    "category": "Automobile",
    "brand": "Tata",
    "fitment": "Tata Altroz",
    "price": 399,
    "rating": 4.5,
    "stock": 48,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=85",
    "description": "Tata Altroz oil filter for Tata Altroz. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Tata Tiago Clutch Kit",
    "category": "Automobile",
    "brand": "Tata",
    "fitment": "Tata Tiago",
    "price": 5999,
    "rating": 4.7,
    "stock": 11,
    "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85",
    "description": "Tata Tiago clutch kit for Tata Tiago. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Mahindra Scorpio N Air Filter",
    "category": "Automobile",
    "brand": "Mahindra",
    "fitment": "Mahindra Scorpio N",
    "price": 899,
    "rating": 4.7,
    "stock": 22,
    "image": "/images/products/Mahindra_Scorpio_N_Air_Filter.jpg",
    "description": "Mahindra Scorpio N air filter for Mahindra Scorpio N. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Mahindra Thar Front Brake Pads",
    "category": "Automobile",
    "brand": "Mahindra",
    "fitment": "Mahindra Thar",
    "price": 2499,
    "rating": 4.8,
    "stock": 19,
    "image": "/images/products/Mahindra_Thar_Front_Brake_Pads.jpg",
    "description": "Mahindra Thar front brake pads for Mahindra Thar. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Mahindra XUV700 Cabin Filter",
    "category": "Automobile",
    "brand": "Mahindra",
    "fitment": "Mahindra XUV700",
    "price": 999,
    "rating": 4.7,
    "stock": 27,
    "image": "/images/products/Mahindra_XUV700_Cabin_Filter.jpg",
    "description": "Mahindra XUV700 cabin filter for Mahindra XUV700. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Mahindra Bolero Oil Filter",
    "category": "Automobile",
    "brand": "Mahindra",
    "fitment": "Mahindra Bolero",
    "price": 449,
    "rating": 4.5,
    "stock": 46,
    "image": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85",
    "description": "Mahindra Bolero oil filter for Mahindra Bolero. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Mahindra Thar Clutch Kit",
    "category": "Automobile",
    "brand": "Mahindra",
    "fitment": "Mahindra Thar",
    "price": 8499,
    "rating": 4.8,
    "stock": 7,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=85",
    "description": "Mahindra Thar clutch kit for Mahindra Thar. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Toyota Innova Crysta Air Filter",
    "category": "Automobile",
    "brand": "Toyota",
    "fitment": "Toyota Innova Crysta",
    "price": 999,
    "rating": 4.8,
    "stock": 23,
    "image": "/images/products/Toyota_Innova_Crysta_Air_Filter.jpg",
    "description": "Toyota Innova Crysta air filter for Toyota Innova Crysta. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Toyota Fortuner Front Brake Pad Set",
    "category": "Automobile",
    "brand": "Toyota",
    "fitment": "Toyota Fortuner",
    "price": 4999,
    "rating": 4.8,
    "stock": 13,
    "image": "/images/products/Toyota_Fortuner_Front_Brake_Pad_Set.jpg",
    "description": "Toyota Fortuner front brake pad set for Toyota Fortuner. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Toyota Glanza Cabin Filter",
    "category": "Automobile",
    "brand": "Toyota",
    "fitment": "Toyota Glanza",
    "price": 749,
    "rating": 4.6,
    "stock": 32,
    "image": "/images/products/Toyota_Glanza_Cabin_Filter.jpg",
    "description": "Toyota Glanza cabin filter for Toyota Glanza. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Toyota Innova Oil Filter",
    "category": "Automobile",
    "brand": "Toyota",
    "fitment": "Toyota Innova",
    "price": 499,
    "rating": 4.7,
    "stock": 41,
    "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85",
    "description": "Toyota Innova oil filter for Toyota Innova. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Kia Seltos Air Filter",
    "category": "Automobile",
    "brand": "Kia",
    "fitment": "Kia Seltos",
    "price": 849,
    "rating": 4.7,
    "stock": 29,
    "image": "/images/products/Kia_Seltos_Air_Filter.jpg",
    "description": "Kia Seltos air filter for Kia Seltos. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Kia Sonet Front Brake Pads",
    "category": "Automobile",
    "brand": "Kia",
    "fitment": "Kia Sonet",
    "price": 2299,
    "rating": 4.7,
    "stock": 21,
    "image": "/images/products/Kia_Sonet_Front_Brake_Pads.jpg",
    "description": "Kia Sonet front brake pads for Kia Sonet. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Kia Carens Cabin Filter",
    "category": "Automobile",
    "brand": "Kia",
    "fitment": "Kia Carens",
    "price": 899,
    "rating": 4.6,
    "stock": 24,
    "image": "/images/products/Kia_Carens_Cabin_Filter.jpg",
    "description": "Kia Carens cabin filter for Kia Carens. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Honda City Air Filter",
    "category": "Automobile",
    "brand": "Honda",
    "fitment": "Honda City",
    "price": 749,
    "rating": 4.7,
    "stock": 36,
    "image": "/images/products/Honda_City_Air_Filter.jpg",
    "description": "Honda City air filter for Honda City. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Honda Amaze Front Brake Pads",
    "category": "Automobile",
    "brand": "Honda",
    "fitment": "Honda Amaze",
    "price": 1999,
    "rating": 4.7,
    "stock": 18,
    "image": "/images/products/Honda_Amaze_Front_Brake_Pads.jpg",
    "description": "Honda Amaze front brake pads for Honda Amaze. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Honda City Clutch Kit",
    "category": "Automobile",
    "brand": "Honda",
    "fitment": "Honda City",
    "price": 7499,
    "rating": 4.8,
    "stock": 8,
    "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85",
    "description": "Honda City clutch kit for Honda City. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Renault Kwid Air Filter",
    "category": "Automobile",
    "brand": "Renault",
    "fitment": "Renault Kwid",
    "price": 599,
    "rating": 4.5,
    "stock": 37,
    "image": "/images/products/Renault_Kwid_Air_Filter.jpg",
    "description": "Renault Kwid air filter for Renault Kwid. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Renault Kwid Front Brake Pad Set",
    "category": "Automobile",
    "brand": "Renault",
    "fitment": "Renault Kwid",
    "price": 1699,
    "rating": 4.6,
    "stock": 26,
    "image": "/images/products/Renault_Kwid_Front_Brake_Pad_Set.jpg",
    "description": "Renault Kwid front brake pad set for Renault Kwid. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Renault Duster Cabin Filter",
    "category": "Automobile",
    "brand": "Renault",
    "fitment": "Renault Duster",
    "price": 849,
    "rating": 4.5,
    "stock": 17,
    "image": "/images/products/Renault_Duster_Cabin_Filter.jpg",
    "description": "Renault Duster cabin filter for Renault Duster. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Nissan Magnite Air Filter",
    "category": "Automobile",
    "brand": "Nissan",
    "fitment": "Nissan Magnite",
    "price": 699,
    "rating": 4.6,
    "stock": 33,
    "image": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85",
    "description": "Nissan Magnite air filter for Nissan Magnite. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Nissan Kicks Front Brake Pads",
    "category": "Automobile",
    "brand": "Nissan",
    "fitment": "Nissan Kicks",
    "price": 2299,
    "rating": 4.6,
    "stock": 14,
    "image": "/images/products/moto_comp_r2_c3.jpg",
    "description": "Nissan Kicks front brake pads for Nissan Kicks. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Volkswagen Polo Air Filter",
    "category": "Automobile",
    "brand": "Volkswagen",
    "fitment": "Volkswagen Polo",
    "price": 899,
    "rating": 4.7,
    "stock": 25,
    "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85",
    "description": "Volkswagen Polo air filter for Volkswagen Polo. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Volkswagen Virtus Front Brake Pads",
    "category": "Automobile",
    "brand": "Volkswagen",
    "fitment": "Volkswagen Virtus",
    "price": 2599,
    "rating": 4.8,
    "stock": 18,
    "image": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85",
    "description": "Volkswagen Virtus front brake pads for Volkswagen Virtus. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Skoda Slavia Cabin Filter",
    "category": "Automobile",
    "brand": "Skoda",
    "fitment": "Skoda Slavia",
    "price": 999,
    "rating": 4.7,
    "stock": 20,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=85",
    "description": "Skoda Slavia cabin filter for Skoda Slavia. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Skoda Kushaq Front Brake Pads",
    "category": "Automobile",
    "brand": "Skoda",
    "fitment": "Skoda Kushaq",
    "price": 2699,
    "rating": 4.8,
    "stock": 15,
    "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85",
    "description": "Skoda Kushaq front brake pads for Skoda Kushaq. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Bosch Premium Petrol Spark Plug Set",
    "category": "Automobile",
    "brand": "Bosch",
    "fitment": "Maruti/Hyundai/Tata petrol engines",
    "price": 1299,
    "rating": 4.8,
    "stock": 45,
    "image": "/images/products/Bosch_Premium_Petrol_Spark_Plug_Set.jpg",
    "description": "Bosch premium petrol spark plug set for Maruti/Hyundai/Tata petrol engines. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Bosch Car Battery 45Ah",
    "category": "Automobile",
    "brand": "Bosch",
    "fitment": "12V passenger cars",
    "price": 5699,
    "rating": 4.7,
    "stock": 12,
    "image": "/images/products/Bosch_Car_Battery_45Ah.jpg",
    "description": "Bosch car battery 45Ah for 12V passenger cars. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Valeo Clutch Kit",
    "category": "Automobile",
    "brand": "Valeo",
    "fitment": "Popular hatchbacks and sedans",
    "price": 7499,
    "rating": 4.8,
    "stock": 10,
    "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85",
    "description": "Valeo clutch kit for Popular hatchbacks and sedans. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Exide Car Battery 35Ah",
    "category": "Automobile",
    "brand": "Exide",
    "fitment": "12V hatchbacks",
    "price": 4599,
    "rating": 4.7,
    "stock": 19,
    "image": "/images/products/Exide_Car_Battery_35Ah.jpg",
    "description": "Exide car battery 35Ah for 12V hatchbacks. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Amaron Car Battery 45Ah",
    "category": "Automobile",
    "brand": "Amaron",
    "fitment": "12V hatchbacks/sedans",
    "price": 5299,
    "rating": 4.8,
    "stock": 17,
    "image": "/images/products/Amaron_Car_Battery_45Ah.jpg",
    "description": "Amaron car battery 45Ah for 12V hatchbacks/sedans. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Lumax LED Headlamp Assembly",
    "category": "Automobile",
    "brand": "Lumax",
    "fitment": "Popular Indian passenger cars",
    "price": 3499,
    "rating": 4.5,
    "stock": 16,
    "image": "/images/products/Lumax_LED_Headlamp_Assembly.jpg",
    "description": "Lumax LED headlamp assembly for Popular Indian passenger cars. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Uno Minda Car Horn Pair",
    "category": "Automobile",
    "brand": "Uno Minda",
    "fitment": "12V passenger cars",
    "price": 899,
    "rating": 4.6,
    "stock": 44,
    "image": "/images/products/Uno_Minda_Car_Horn_Pair.jpg",
    "description": "Uno Minda car horn pair for 12V passenger cars. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "NGK Laser Iridium Spark Plug Set",
    "category": "Automobile",
    "brand": "NGK",
    "fitment": "Modern petrol engines",
    "price": 2199,
    "rating": 4.9,
    "stock": 31,
    "image": "/images/products/NGK_Laser_Iridium_Spark_Plug_Set.jpg",
    "description": "NGK laser iridium spark plug set for Modern petrol engines. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "SKF Front Wheel Bearing Kit",
    "category": "Automobile",
    "brand": "SKF",
    "fitment": "Maruti/Hyundai/Tata applications",
    "price": 1499,
    "rating": 4.7,
    "stock": 22,
    "image": "/images/products/auto_main_r4_c7.jpg",
    "description": "SKF front wheel bearing kit for Maruti/Hyundai/Tata applications. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Monroe Front Shock Absorber Pair",
    "category": "Automobile",
    "brand": "Monroe",
    "fitment": "Popular passenger cars",
    "price": 6499,
    "rating": 4.7,
    "stock": 9,
    "image": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85",
    "description": "Monroe front shock absorber pair for Popular passenger cars. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  },
  {
    "name": "Denso Radiator Cooling Fan Motor",
    "category": "Automobile",
    "brand": "Denso",
    "fitment": "Popular passenger cars",
    "price": 3899,
    "rating": 4.6,
    "stock": 13,
    "image": "/images/products/Denso_Radiator_Cooling_Fan_Motor.jpg",
    "description": "Denso radiator cooling fan motor for Popular passenger cars. Quality replacement spare selected for dependable fit, everyday durability and service performance."
  }
];
