import React,{useEffect,useState} from 'react';
import {collection,onSnapshot,query,where} from 'firebase/firestore';
import {auth,db} from './firebase';
import {Package,ChevronDown,MapPin,Truck,CheckCircle,Clock,XCircle,RotateCcw,History} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {toast} from 'react-hot-toast';
import './orders.css';
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const steps=['placed','confirmed','packed','shipped','out_for_delivery','delivered'];
const labels={placed:'Order placed',confirmed:'Confirmed',packed:'Packed',shipped:'Shipped',out_for_delivery:'Out for delivery',delivered:'Delivered',cancelled:'Cancelled'};
const formatDate=value=>{try{const d=value?.toDate?value.toDate():value?new Date(value):null;return d&& !Number.isNaN(d.getTime())?d.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'Recently'}catch{return'Recently'}};
export default function Orders(){const nav=useNavigate(),[orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(null);useEffect(()=>{const u=auth.currentUser;if(!u){setLoading(false);return}const q=query(collection(db,'orders'),where('userId','==',u.uid));const unsubscribe=onSnapshot(q,snap=>{const next=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>{const ad=a.createdAt?.toMillis?a.createdAt.toMillis():0,bd=b.createdAt?.toMillis?b.createdAt.toMillis():0;return bd-ad});setOrders(next);setLoading(false)},e=>{console.error(e);toast.error('Could not load your orders.');setLoading(false)});return()=>unsubscribe()},[]);
return <section className="page ordersPage"><div className="pagehead"><p className="eyebrow">YOUR ORDERS</p><h1>Order <span>history.</span></h1><p>Track your purchases and check delivery details. Status updates appear here automatically.</p></div>{loading?<div className="empty">Loading your orders...</div>:!orders.length?<div className="ordersEmpty"><Package size={42}/><h2>No orders yet</h2><p>Your completed purchases will appear here.</p><button className="heroBtn" onClick={()=>nav('/products')}>Start Shopping</button></div>:<div className="customerOrders">{orders.map(o=>{const status=o.orderStatus||'placed',cancelled=status==='cancelled',idx=steps.indexOf(status),history=Array.isArray(o.statusHistory)?[...o.statusHistory].reverse():[];return <article className="customerOrder" key={o.id}><div className="customerOrderTop"><div><b>{o.orderId||o.id}</b><small>{o.customer?.name||'Customer'} · {formatDate(o.createdAt)}</small></div><strong>{money(o.total)}</strong><span className={`status ${status}`}>{cancelled?<XCircle size={14}/>:status==='delivered'?<CheckCircle size={14}/>:<Clock size={14}/>} {labels[status]||status.replaceAll('_',' ')}</span><button className="orderToggle" onClick={()=>setOpen(open===o.id?null:o.id)} aria-label="Show order details"><ChevronDown size={18}/></button></div>{!cancelled&&<div className="orderProgress">{steps.map((s,i)=><div className={i<=idx?'done':''} key={s}><i></i><small>{labels[s]}</small></div>)}</div>}{open===o.id&&<div className="customerOrderDetails"><div className="customerAddress"><h3><MapPin size={16}/> Delivery</h3><p>{o.shipping?.address||'—'}, {o.shipping?.city||'—'}, {o.shipping?.state||'—'} - {o.shipping?.pincode||'—'}</p></div><div><h3><Truck size={16}/> Items</h3>{(o.items||[]).map((x,i)=><div className="customerItem" key={i}><img src={x.image} alt=""/><span><b>{x.name}</b><small>Qty {x.qty}</small></span><strong>{money(x.price*x.qty)}</strong></div>)}</div>{history.length>0&&<div className="statusHistory"><h3><History size={16}/> Tracking history</h3><div className="historyList">{history.map((h,i)=><div className="historyItem" key={`${h.status}-${i}`}><span className="historyDot"></span><div><b>{labels[h.status]||String(h.status||'').replaceAll('_',' ')}</b><small>{formatDate(h.updatedAt)}</small></div></div>)}</div></div>}{cancelled&&<div className="afterSales"><h3><XCircle size={16}/> Order cancelled</h3><p>This order has been cancelled. If you need help, please contact MOTO DC support.</p></div>}{status==='delivered'&&<div className="afterSales"><h3>Need help with this order?</h3><p>If an item arrived damaged, defective, or mismatched, you can request a return or replacement.</p><button onClick={()=>nav('/returns')}><RotateCcw size={15}/> Return / Replacement</button></div>}</div>}</article>})}</div>}</section>}
