import React,{useEffect,useState} from 'react';
import {collection,onSnapshot,query,where} from 'firebase/firestore';
import {auth,db} from './firebase';
import {Package,ChevronDown,MapPin,Truck,CheckCircle,Clock,XCircle,RotateCcw,History,Download} from 'lucide-react';
import {jsPDF} from 'jspdf';
import {useNavigate} from 'react-router-dom';
import {toast} from 'react-hot-toast';
import './orders.css';
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const steps=['placed','confirmed','packed','shipped','out_for_delivery','delivered'];
const labels={placed:'Order placed',confirmed:'Confirmed',packed:'Packed',shipped:'Shipped',out_for_delivery:'Out for delivery',delivered:'Delivered',cancelled:'Cancelled'};
const formatDate=value=>{try{const d=value?.toDate?value.toDate():value?new Date(value):null;return d&&!Number.isNaN(d.getTime())?d.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'Recently'}catch{return'Recently'}};
const safeText=value=>String(value??'').replace(/[\r\n]+/g,' ').trim();
function downloadInvoice(o){try{const pdf=new jsPDF();const pageW=pdf.internal.pageSize.getWidth();const margin=16;let y=18;const line=(text,x=margin,size=10,bold=false)=>{pdf.setFont('helvetica',bold?'bold':'normal');pdf.setFontSize(size);pdf.text(safeText(text),x,y);y+=6};
 pdf.setFont('helvetica','bold');pdf.setFontSize(24);pdf.text('MOTO DC',margin,y);pdf.setFontSize(11);pdf.setFont('helvetica','normal');pdf.text('AUTOMOTIVE PARTS',margin,y+7);pdf.setFont('helvetica','bold');pdf.setFontSize(18);pdf.text('INVOICE',pageW-margin,y,{align:'right'});y+=22;
 pdf.setDrawColor(210);pdf.line(margin,y,pageW-margin,y);y+=10;
 const date=formatDate(o.createdAt);line(`Invoice / Order ID: ${o.orderId||o.id}`,margin,10,true);line(`Order date: ${date}`,margin,9,false);line(`Payment: ${o.paymentMethod==='cod'?'Cash on Delivery':'Online Payment'} · ${o.paymentStatus||'pending'}`,margin,9,false);y+=4;
 pdf.setFont('helvetica','bold');pdf.setFontSize(11);pdf.text('BILL TO',margin,y);y+=7;line(o.customer?.name||'Customer',margin,10,true);if(o.customer?.email)line(o.customer.email,margin,9);if(o.customer?.phone)line(o.customer.phone,margin,9);const address=[o.shipping?.address,o.shipping?.city,o.shipping?.state,o.shipping?.pincode].filter(Boolean).join(', ');if(address){const wrapped=pdf.splitTextToSize(address,pageW-margin*2);pdf.setFont('helvetica','normal');pdf.setFontSize(9);pdf.text(wrapped,margin,y);y+=wrapped.length*5+5;}y+=4;
 const colX=[margin,92,132,pageW-margin];pdf.setFillColor(242,243,245);pdf.rect(margin,y-5,pageW-margin*2,9,'F');pdf.setFont('helvetica','bold');pdf.setFontSize(9);pdf.text('ITEM',colX[0]+2,y);pdf.text('QTY',colX[1]+2,y);pdf.text('PRICE',colX[2]+2,y);pdf.text('TOTAL',colX[3]-2,y,{align:'right'});y+=9;
 (o.items||[]).forEach(item=>{const name=pdf.splitTextToSize(safeText(item.name||'Item'),82);if(y+name.length*5>260){pdf.addPage();y=18;}pdf.setFont('helvetica','normal');pdf.setFontSize(9);pdf.text(name,colX[0]+2,y);pdf.text(String(item.qty||1),colX[1]+2,y);pdf.text(`Rs. ${Number(item.price||0).toLocaleString('en-IN')}`,colX[2]+2,y);pdf.text(`Rs. ${(Number(item.price||0)*Number(item.qty||1)).toLocaleString('en-IN')}`,colX[3]-2,y,{align:'right'});y+=Math.max(7,name.length*5);pdf.setDrawColor(225);pdf.line(margin,y-3,pageW-margin,y-3);});
 y+=7;const subtotal=Number(o.subtotal??o.total??0),delivery=Number(o.delivery||0);pdf.setFont('helvetica','normal');pdf.setFontSize(10);pdf.text('Subtotal',pageW-80,y);pdf.text(`Rs. ${subtotal.toLocaleString('en-IN')}`,pageW-margin,y,{align:'right'});y+=7;pdf.text('Delivery',pageW-80,y);pdf.text(delivery?'Rs. '+delivery.toLocaleString('en-IN'):'FREE',pageW-margin,y,{align:'right'});y+=9;pdf.setFont('helvetica','bold');pdf.setFontSize(13);pdf.text('TOTAL',pageW-80,y);pdf.text(`Rs. ${Number(o.total||0).toLocaleString('en-IN')}`,pageW-margin,y,{align:'right'});y+=14;pdf.setFont('helvetica','normal');pdf.setFontSize(8);pdf.setTextColor(110);pdf.text('Thank you for shopping with MOTO DC.',margin,y);pdf.text('This is a computer-generated invoice.',margin,y+5);pdf.save(`MOTO-DC-Invoice-${safeText(o.orderId||o.id).replace(/[^a-z0-9_-]/gi,'-')}.pdf`);toast.success('Invoice downloaded');}catch(e){console.error(e);toast.error('Could not generate invoice');}}
export default function Orders(){const nav=useNavigate(),[orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(null);useEffect(()=>{const u=auth.currentUser;if(!u){setLoading(false);return}const queries=[query(collection(db,'orders','cod orders','records'),where('userId','==',u.uid)),query(collection(db,'orders','online orders','records'),where('userId','==',u.uid))];let active=true;const lists=[[],[]];const unsubs=queries.map((q,i)=>onSnapshot(q,snap=>{lists[i]=snap.docs.map(d=>({id:d.id,...d.data()}));const next=[...lists[0],...lists[1]].sort((a,b)=>{const ad=a.createdAt?.toMillis?a.createdAt.toMillis():0,bd=b.createdAt?.toMillis?b.createdAt.toMillis():0;return bd-ad});if(active){setOrders(next);setLoading(false)}},e=>{console.error(e);if(active){toast.error('Could not load your orders.');setLoading(false)}}));return()=>{active=false;unsubs.forEach(u=>u())}},[]);
return <section className="page ordersPage"><div className="pagehead"><p className="eyebrow">YOUR ORDERS</p><h1>Order <span>history.</span></h1><p>Track your purchases, download invoices and check delivery details. Status updates appear here automatically.</p></div>{loading?<div className="empty">Loading your orders...</div>:!orders.length?<div className="ordersEmpty"><Package size={42}/><h2>No orders yet</h2><p>Your completed purchases will appear here.</p><button className="heroBtn" onClick={()=>nav('/products')}>Start Shopping</button></div>:<div className="customerOrders">{orders.map(o=>{const status=o.orderStatus||'placed',cancelled=status==='cancelled',idx=steps.indexOf(status),history=Array.isArray(o.statusHistory)?[...o.statusHistory].reverse():[];return <article className="customerOrder" key={o.id}><div className="customerOrderTop"><div><b>{o.orderId||o.id}</b><small>{o.customer?.name||'Customer'} · {formatDate(o.createdAt)}</small></div><strong>{money(o.total)}</strong><span className={`status ${status}`}>{cancelled?<XCircle size={14}/>:status==='delivered'?<CheckCircle size={14}/>:<Clock size={14}/>} {labels[status]||status.replaceAll('_',' ')}</span><button className="orderToggle" onClick={()=>setOpen(open===o.id?null:o.id)} aria-label="Show order details"><ChevronDown size={18}/></button></div>{!cancelled&&<div className="orderProgress">{steps.map((s,i)=><div className={i<=idx?'done':''} key={s}><i></i><small>{labels[s]}</small></div>)}</div>}{open===o.id&&<div className="customerOrderDetails"><div className="customerAddress"><h3><MapPin size={16}/> Delivery</h3><p>{o.shipping?.address||'—'}, {o.shipping?.city||'—'}, {o.shipping?.state||'—'} - {o.shipping?.pincode||'—'}</p></div><div><h3><Truck size={16}/> Items</h3>{(o.items||[]).map((x,i)=><div className="customerItem" key={i}><img src={x.image} alt=""/><span><b>{x.name}</b><small>Qty {x.qty}</small></span><strong>{money(x.price*x.qty)}</strong></div>)}</div><div className="invoiceActions"><button onClick={()=>downloadInvoice(o)}><Download size={15}/> Download Invoice (PDF)</button></div>{history.length>0&&<div className="statusHistory"><h3><History size={16}/> Tracking history</h3><div className="historyList">{history.map((h,i)=><div className="historyItem" key={`${h.status}-${i}`}><span className="historyDot"></span><div><b>{labels[h.status]||String(h.status||'').replaceAll('_',' ')}</b><small>{formatDate(h.updatedAt)}</small></div></div>)}</div></div>}{cancelled&&<div className="afterSales"><h3><XCircle size={16}/> Order cancelled</h3><p>This order has been cancelled. If you need help, please contact MOTO DC support.</p></div>}{status==='delivered'&&<div className="afterSales"><h3>Need help with this order?</h3><p>If an item arrived damaged, defective, or mismatched, you can request a return or replacement.</p><button onClick={()=>nav('/returns')}><RotateCcw size={15}/> Return / Replacement</button></div>}</div>}</article>})}</div>}</section>}
