import React,{useEffect,useState} from 'react';
import {collection,getDocs,orderBy,query,where} from 'firebase/firestore';
import {auth,db} from './firebase';
import {Package,ChevronDown,MapPin,Truck,CheckCircle,Clock,XCircle,RotateCcw,RefreshCw} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {toast} from 'react-hot-toast';
import './orders.css';
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const steps=['placed','confirmed','packed','shipped','delivered'];
const labels={placed:'Order placed',confirmed:'Confirmed',packed:'Packed',shipped:'Shipped',delivered:'Delivered',cancelled:'Cancelled'};
export default function Orders(){const nav=useNavigate(),[orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(null);useEffect(()=>{let active=true;(async()=>{const u=auth.currentUser;if(!u){setLoading(false);return}try{const snap=await getDocs(query(collection(db,'orders'),where('userId','==',u.uid),orderBy('createdAt','desc')));if(active)setOrders(snap.docs.map(d=>({id:d.id,...d.data()})))}catch(e){console.error(e);toast.error(e.code==='failed-precondition'?'Please create the Firestore index for customer orders.':'Could not load your orders.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
return <section className="page ordersPage"><div className="pagehead"><p className="eyebrow">YOUR ORDERS</p><h1>Order <span>history.</span></h1><p>Track your purchases and check delivery details.</p></div>{loading?<div className="empty">Loading your orders...</div>:!orders.length?<div className="ordersEmpty"><Package size={42}/><h2>No orders yet</h2><p>Your completed purchases will appear here.</p><button className="heroBtn" onClick={()=>nav('/products')}>Start Shopping</button></div>:<div className="customerOrders">{orders.map(o=>{const status=o.orderStatus||'placed',cancelled=status==='cancelled',idx=steps.indexOf(status);return <article className="customerOrder" key={o.id}><div className="customerOrderTop"><div><b>{o.orderId||o.id}</b><small>{o.customer?.name} · {o.createdAt?.toDate?o.createdAt.toDate().toLocaleDateString('en-IN'): 'Recently'}</small></div><strong>{money(o.total)}</strong><span className={`status ${status}`}>{cancelled?<XCircle size={14}/>:status==='delivered'?<CheckCircle size={14}/>:<Clock size={14}/>} {labels[status]||status}</span><button className="orderToggle" onClick={()=>setOpen(open===o.id?null:o.id)}><ChevronDown size={18}/></button></div>{!cancelled&&<div className="orderProgress">{steps.map((s,i)=><div className={i<=idx?'done':''} key={s}><i></i><small>{labels[s]}</small></div>)}</div>}{open===o.id&&<div className="customerOrderDetails"><div className="customerAddress"><h3><MapPin size={16}/> Delivery</h3><p>{o.shipping?.address}, {o.shipping?.city}, {o.shipping?.state} - {o.shipping?.pincode}</p></div><div><h3><Truck size={16}/> Items</h3>{(o.items||[]).map((x,i)=><div className="customerItem" key={i}><img src={x.image} alt=""/><span><b>{x.name}</b><small>Qty {x.qty}</small></span><strong>{money(x.price*x.qty)}</strong></div>)}</div>{status==='delivered'&&<div className="afterSales"><h3>Need help with this order?</h3><p>If an item arrived damaged, defective, or mismatched, you can request a return or replacement.</p><button onClick={()=>nav('/returns')}><RotateCcw size={15}/> Return / Replacement</button></div>}</div>}</article>})}</div>}</section>}
