import React,{useEffect,useState} from 'react';
import {collection,addDoc,query,where,onSnapshot,getDocs,setDoc,doc} from 'firebase/firestore';
import {auth,db} from './firebase';
import {Package,RotateCcw,RefreshCw} from 'lucide-react';
import {toast} from 'react-hot-toast';
import './orders.css';

const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const sortNewest=xs=>xs.sort((a,b)=>{const av=a.createdAt?.toMillis?a.createdAt.toMillis():new Date(a.createdAt||0).getTime();const bv=b.createdAt?.toMillis?b.createdAt.toMillis():new Date(b.createdAt||0).getTime();return bv-av});
const groupFor=payment=>String(payment||'cod').toLowerCase()==='online'?'online request':'cod request';
const typeCollection=type=>type==='replacement'?'replacement':'return';

export default function Returns(){
 const [orders,setOrders]=useState([]),[requests,setRequests]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 useEffect(()=>{const u=auth.currentUser;if(!u){setLoading(false);return}let active=true;const loadOrders=async()=>{try{const [cod,online]=await Promise.all([getDocs(query(collection(db,'orders','cod orders','records'),where('userId','==',u.uid),where('orderStatus','==','delivered'))),getDocs(query(collection(db,'orders','online orders','records'),where('userId','==',u.uid),where('orderStatus','==','delivered')))]);if(active)setOrders(sortNewest([...cod.docs,...online.docs].map(d=>({id:d.id,...d.data()}))))}catch(e){console.error(e);toast.error('Could not load delivered orders')}finally{if(active)setLoading(false)}};loadOrders();const groups=[['cod request','return'],['cod request','replacement'],['online request','return'],['online request','replacement']];const lists=groups.map(()=>[]);const unsubs=groups.map(([group,type],i)=>onSnapshot(query(collection(db,'request',group,type),where('userId','==',u.uid)),snap=>{lists[i]=snap.docs.map(d=>({id:d.id,requestGroup:group,requestCollection:type,...d.data()}));if(active)setRequests(sortNewest(lists.flat()))},e=>{console.error(e);toast.error('Could not listen for return request updates')}));return()=>{active=false;unsubs.forEach(x=>x())}},[]);
 const request=async(o,type)=>{if(busy)return;const existing=requests.find(r=>r.orderId===o.id&&['requested','approved','processing'].includes(r.status));if(existing){toast.error('A request is already active for this order');return}setBusy(o.id+type);try{const payment=String(o.paymentMethod||'cod').toLowerCase()==='online'?'online':'cod';const group=groupFor(payment);const sub=typeCollection(type);await setDoc(doc(db,'request',group),{name:group,paymentMethod:payment,updatedAt:new Date()},{merge:true});await setDoc(doc(db,'request',group,sub),{name:`${payment} ${sub}`,paymentMethod:payment,type:sub,updatedAt:new Date()},{merge:true});await addDoc(collection(db,'request',group,sub),{userId:auth.currentUser.uid,orderId:o.id,displayOrderId:o.orderId||o.id,type,paymentMethod:payment,requestGroup:group,requestCollection:sub,reason:'Customer reported a mismatch or damage',status:'requested',customer:o.customer||{},shipping:o.shipping||{},items:o.items||[],total:Number(o.total||0),createdAt:new Date()});toast.success(`${type==='replacement'?'Replacement':'Return'} request submitted`)}catch(e){console.error(e);toast.error('Could not submit the request.')}finally{setBusy('')}};
 return <section className="page ordersPage"><div className="pagehead"><p className="eyebrow">AFTER-SALES SUPPORT</p><h1>Returns & <span>replacement.</span></h1><p>Request help if an item arrived damaged, defective, or mismatched.</p></div>{loading?<div className="empty">Loading...</div>:<><div className="customerOrders">{orders.map(o=><article className="customerOrder" key={o.id}><div className="customerOrderTop"><div><b>{o.orderId||o.id}</b><small>{o.customer?.name||'Customer'} · {o.createdAt?.toDate?o.createdAt.toDate().toLocaleDateString('en-IN'):'Recently'}</small></div><strong>{money(o.total)}</strong><span className="status delivered"><Package size={14}/> Delivered</span></div><div className="returnActions"><button onClick={()=>request(o,'return')} disabled={busy.startsWith(o.id)}><RotateCcw size={16}/> {busy===o.id+'return'?'Submitting...':'Return'}</button><button onClick={()=>request(o,'replacement')} disabled={busy.startsWith(o.id)}><RefreshCw size={16}/> {busy===o.id+'replacement'?'Submitting...':'Replacement'}</button></div></article>)}</div>{!orders.length&&<div className="ordersEmpty"><Package size={40}/><h2>No delivered orders</h2><p>Delivered purchases will appear here when they become eligible for support.</p></div>}<div className="dashPanel returnHistory"><div className="dashPanelHead"><h3>Request history</h3></div>{requests.length?requests.map(r=><div className="returnRow" key={`${r.requestGroup}-${r.requestCollection}-${r.id}`}><b>{r.displayOrderId}</b><span>{r.type==='replacement'?'Replacement':'Return'}</span><strong>{r.status}</strong></div>):<p className="dashMuted">No return or replacement requests yet.</p>}</div></>}</section>;
}
