import React,{useEffect,useState} from 'react';
import {collection,getDocs,addDoc,query,where,orderBy} from 'firebase/firestore';
import {auth,db} from './firebase';
import {Package,RotateCcw,RefreshCw} from 'lucide-react';
import {toast} from 'react-hot-toast';
import './orders.css';
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
export default function Returns(){
 const [orders,setOrders]=useState([]),[requests,setRequests]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 const load=async()=>{const u=auth.currentUser;if(!u){setLoading(false);return}setLoading(true);try{const [os,rs]=await Promise.all([getDocs(query(collection(db,'orders'),where('userId','==',u.uid),where('orderStatus','==','delivered'),orderBy('createdAt','desc'))),getDocs(query(collection(db,'returns'),where('userId','==',u.uid),orderBy('createdAt','desc')))]);setOrders(os.docs.map(d=>({id:d.id,...d.data()})));setRequests(rs.docs.map(d=>({id:d.id,...d.data()})))}catch(e){console.error(e);toast.error(e.code==='failed-precondition'?'Please create the Firestore indexes for returns and delivered orders.':'Could not load return requests.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const request=async(o,type)=>{if(busy)return;const existing=requests.find(r=>r.orderId===o.id&&['requested','approved','processing'].includes(r.status));if(existing){toast.error('A request is already active for this order');return}setBusy(o.id+type);try{await addDoc(collection(db,'returns'),{userId:auth.currentUser.uid,orderId:o.id,displayOrderId:o.orderId||o.id,type,reason:'Customer reported a mismatch or damage',status:'requested',customer:o.customer||{},shipping:o.shipping||{},items:o.items||[],total:Number(o.total||0),createdAt:new Date()});toast.success(`${type==='replacement'?'Replacement':'Return'} request submitted`);await load()}catch(e){console.error(e);toast.error('Could not submit the request.')}finally{setBusy('')}};
 return <section className="page ordersPage"><div className="pagehead"><p className="eyebrow">AFTER-SALES SUPPORT</p><h1>Returns & <span>replacement.</span></h1><p>Request help if an item arrived damaged, defective, or mismatched.</p></div>{loading?<div className="empty">Loading...</div>:<><div className="customerOrders">{orders.map(o=><article className="customerOrder" key={o.id}><div className="customerOrderTop"><div><b>{o.orderId||o.id}</b><small>{o.customer?.name||'Customer'} · {o.createdAt?.toDate?o.createdAt.toDate().toLocaleDateString('en-IN'):'Recently'}</small></div><strong>{money(o.total)}</strong><span className="status delivered"><Package size={14}/> Delivered</span></div><div className="returnActions"><button onClick={()=>request(o,'return')} disabled={busy.startsWith(o.id)}><RotateCcw size={16}/> {busy===o.id+'return'?'Submitting...':'Return'}</button><button onClick={()=>request(o,'replacement')} disabled={busy.startsWith(o.id)}><RefreshCw size={16}/> {busy===o.id+'replacement'?'Submitting...':'Replacement'}</button></div></article>)}</div>{!orders.length&&<div className="ordersEmpty"><Package size={40}/><h2>No delivered orders</h2><p>Delivered purchases will appear here when they become eligible for support.</p></div>}<div className="dashPanel returnHistory"><div className="dashPanelHead"><h3>Request history</h3></div>{requests.length?requests.map(r=><div className="returnRow" key={r.id}><b>{r.displayOrderId}</b><span>{r.type==='replacement'?'Replacement':'Return'}</span><strong>{r.status}</strong></div>):<p className="dashMuted">No return or replacement requests yet.</p>}</div></>}</section>;
}
